version: "3"

services:
  app:
    build: .
    container_name: arcade
    command: python -u ./run.py
    restart: unless-stopped
    ports:
      #- "5000:5000"
      - "80:80"
    external_links:
      - postgres_cntr
    environment:
      - "ENV=CONTAINER"
      - "PORT=80"
    networks:
      network1:

networks:
  network1:
      external:
        name: network1