"""empty message

Revision ID: 586452eea3bf
Revises: 
Create Date: 2021-07-29 18:23:58.154724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586452eea3bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tema')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id_doc_type', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_doc_type'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('sys_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cli_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sys_user', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('numero_cartao', sa.String(length=255), nullable=False),
    sa.Column('credito', sa.Float(), nullable=False),
    sa.Column('freeplay_data_exp', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['id_sys_user'], ['sys_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pessoa'),
    sa.UniqueConstraint('numero_cartao')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('id_sys_user', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_sys_user'], ['sys_usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_tema'], ['temas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('log_maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id_sys_user', sa.Integer(), nullable=True),
    sa.Column('id_cli_user', sa.Integer(), nullable=True),
    sa.Column('id_maquina', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cli_user'], ['cli_usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['id_sys_user'], ['sys_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id_sys_user', sa.Integer(), nullable=True),
    sa.Column('id_cli_user', sa.Integer(), nullable=True),
    sa.Column('credito', sa.Float(), nullable=False),
    sa.Column('free_play_days', sa.Integer(), nullable=True),
    sa.Column('credito_pago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cli_user'], ['cli_usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_sys_user'], ['sys_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_vendas')
    op.drop_table('log_maquinas')
    op.drop_table('maquinas')
    op.drop_table('cli_usuarios')
    op.drop_table('sys_usuarios')
    op.drop_table('pessoas')
    op.drop_table('temas')
    op.drop_table('documentos')
    # ### end Alembic commands ###
