"""empty message

Revision ID: 639d57b95a5c
Revises: 64eaa0e2b15a
Create Date: 2021-04-01 16:15:21.874125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d57b95a5c'
down_revision = '64eaa0e2b15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoas', 'id_doc_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoas', 'id_doc_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
